from enum import Enum


class EnumTypeEffet(Enum):
    arme = "arme"
    armure = "armure"
    objet = "objet"
    effet = "effet"


class EnumEffet(Enum):
    arme_a_deux_mains = "arme_a_deux_mains"
    attaque_empoisonnee = "attaque_empoisonnee"
    attaque_enflammee = "attaque_enflammee"
    attaque_enflammee_double_degat = "attaque_enflammee_double_degat"
    attaque_de_dos = "attaque_de_dos"
    attaque_de_flanc = "attaque_de_flanc"
    aura = "aura"
    bonus_de_rang = "bonus_de_rang"
    charge = "charge"
    charge_feroce = "charge_feroce"
    combat_sur_deux_rangs = "combat_sur_deux_rangs"
    coup_fatal = "coup_fatal"
    degat_magique = "degat_magique"
    ethere = "ethere"
    ethere_insensible_degat = "ethere_insensible_degat"
    flanquee = "flanquee"
    frappe_en_dernier = "frappe_en_dernier"
    frappe_en_premier = "frappe_en_premier"
    haine = "haine"
    horde = "horde"
    implacable = "implacable"
    inflammable = "inflammable"
    insensible_au_coup_fatal = "insensible_au_coup_fatal"
    insensible_au_poison = "insensible_au_poison"
    peur = "peur"
    premier_tour = "premier_tour"
    deuxieme_tour = "deuxieme_tour"
    regeneration = "regeneration"
    terreur = "terreur"
    tirailleur = "tirailleur"


class EnumArme(Enum):
    arme_de_base = "arme_de_base"
    deux_armes_de_base = "deux_armes_de_base"
    lance = "lance"
    lance_montee = "lance_montee"
    lance_de_cavalerie = "lance_de_cavalerie"
    arme_lourde = "arme_lourde"
    arme_lourde_montee = "arme_lourde_montee"
    hallebarde = "hallebarde"
    fleau = "fleau"
    fleau_bonus = "fleau_bonus"
    morgenstern = "morgenstern"
    morgenstern_bonus = "morgenstern_bonus"
    marteau_de_cavalerie = "marteau_de_cavalerie"
    marteau_de_cavalerie_bonus = "marteau_de_cavalerie_bonus"
    pistolet = "pistolet"
